name: linkup
description: LinkUp Mobile Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  http: ^0.13.4
  flutter_local_notifications: ^9.4.0
  uuid: ^3.0.6
  flutter_secure_storage: ^5.0.2
  flutter_datetime_picker: ^1.5.1
  fluttertoast: ^8.0.9
  page_transition: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Larsseit
      fonts:
        - asset: assets/fonts/Larsseit.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Text.ttf
